set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/zig-linux-toolchain.cmake")

set(CMAKE_C_COMPILER "zig" cc)
set(CMAKE_CXX_COMPILER "zig" c++)

set(CMAKE_C_COMPILER_TARGET "x86_64-linux-gnu")
set(CMAKE_CXX_COMPILER_TARGET "x86_64-linux-gnu")

set(CMAKE_AR "zig-ar.sh")
set(CMAKE_RANLIB "zig-ranlib.sh")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)