set(CMAKE_C_COMPILER "zig" cc)
set(CMAKE_CXX_COMPILER "zig" c++)

set(CMAKE_C_COMPILER_TARGET "x86_64-windows-gnu")
set(CMAKE_CXX_COMPILER_TARGET "x86_64-windows-gnu")

set(CMAKE_AR "zig-ar.sh")
set(CMAKE_RANLIB "zig-ranlib.sh")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)